/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Command scalemodel fits resource models to committed sweep runs and reports
// how well they predict points held out of their own fit.
//
// It exists so that published sizing figures and the runtime capacity signal
// come from one piece of arithmetic rather than two (SC-018). A table
// hand-derived from a sweep and a process reporting its own position against a
// separately-derived limit would disagree eventually, and the disagreement
// would surface as an operator's deployment behaving unlike its documentation.
//
// Reading committed JSON rather than measuring: the measurement needs a real
// kcp and takes minutes; the fit is arithmetic over its output. Separating them
// means the model can be re-derived, corrected and argued with without
// re-running anything, and that the evidence a figure came from stays in the
// repository next to the figure.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"

	"github.com/jimmidyson/kcp-cluster-api/internal/scaleharness"
)

func main() {
	runsDir := flag.String("runs", "specs/20260815-211812-workspace-wiring-scale/evidence",
		"Directory of committed sweep runs (baseline-*.json).")
	out := flag.String("out", "",
		"Where to write the report. Empty writes to stdout.")
	projectTo := flag.String("project-to", "100,250,500,1000",
		"Comma-separated fleet sizes to project, for sizing guidance.")
	flag.Parse()

	fleets, err := parseInts(*projectTo)
	if err != nil {
		fail(err)
	}

	runs, err := loadRuns(*runsDir)
	if err != nil {
		fail(err)
	}
	if len(runs) == 0 {
		fail(fmt.Errorf("no sweep runs in %s: there is nothing to fit", *runsDir))
	}

	report, err := buildReport(runs, fleets)
	if err != nil {
		fail(err)
	}

	if *out == "" {
		fmt.Print(report)
		return
	}
	if err := os.WriteFile(*out, []byte(report), 0o644); err != nil {
		fail(fmt.Errorf("writing %s: %w", *out, err))
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "scalemodel: %v\n", err)
	os.Exit(1)
}

func loadRuns(dir string) ([]scaleharness.SweepRun, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "baseline-*.json"))
	if err != nil {
		return nil, err
	}
	slices.Sort(paths)

	var runs []scaleharness.SweepRun
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, fmt.Errorf("reading %s: %w", p, err)
		}
		var run scaleharness.SweepRun
		if err := json.Unmarshal(data, &run); err != nil {
			return nil, fmt.Errorf("parsing %s: %w", p, err)
		}
		runs = append(runs, run)
	}
	return runs, nil
}

func buildReport(runs []scaleharness.SweepRun, fleets []int) (string, error) {
	var b strings.Builder

	b.WriteString("# Fitted resource models and held-out accuracy\n\n")
	b.WriteString("Generated by `cmd/scalemodel` from the committed sweep runs in this\n")
	b.WriteString("directory. Do not edit by hand — re-run the tool.\n\n")
	b.WriteString("Every figure below is a projection from what was actually measured. The\n")
	b.WriteString("extrapolation factor says how far past that a figure reaches, and is the\n")
	b.WriteString("number to discount it by.\n\n")

	for _, run := range runs {
		m, err := scaleharness.Fit(run)
		if err != nil {
			return "", fmt.Errorf("fitting %s: %w", run.Summary(), err)
		}

		fmt.Fprintf(&b, "## %s, %d listener(s) per workspace\n\n",
			m.Regime.Shape.Profile, m.Regime.Shape.ListenersPerWorkspace)
		fmt.Fprintf(&b, "%s\n\n", m.Summary())

		fmt.Fprintf(&b, "| Coefficient | Base | Per workspace | R² |\n|---|---|---|---|\n")
		fmt.Fprintf(&b, "| Live heap | %s | %s | %.5f |\n",
			humanBytes(m.Heap.Base), humanBytes(m.Heap.PerWorkspace), m.Heap.RSquared)
		if m.Process != nil {
			fmt.Fprintf(&b, "| Process footprint (`MemStats.Sys`) | %s | %s | %.5f |\n",
				humanBytes(m.Process.Base), humanBytes(m.Process.PerWorkspace), m.Process.RSquared)
		}
		if m.Stack != nil {
			fmt.Fprintf(&b, "| Goroutine stacks | %s | %s | %.5f |\n",
				humanBytes(m.Stack.Base), humanBytes(m.Stack.PerWorkspace), m.Stack.RSquared)
		}
		fmt.Fprintf(&b, "| Goroutines | %.0f | %.2f | %.5f |\n\n",
			m.Goroutines.Base, m.Goroutines.PerWorkspace, m.Goroutines.RSquared)

		if m.Process != nil {
			fmt.Fprintf(&b, "Footprint per workspace is **%.1f×** the live-heap figure. Sizing from heap\n"+
				"alone would under-provision by that multiple.\n\n",
				m.Process.PerWorkspace/m.Heap.PerWorkspace)
		}

		writeHoldOut(&b, run)
		writeProjection(&b, m, fleets)

		b.WriteString("**Not modelled.**\n\n")
		for _, u := range m.Unmodelled {
			fmt.Fprintf(&b, "- %s\n", u)
		}
		b.WriteString("\n")
	}
	return b.String(), nil
}

func writeHoldOut(b *strings.Builder, run scaleharness.SweepRun) {
	vs, err := scaleharness.HoldOut(run)
	if err != nil {
		// Not fatal: a sweep too short to validate is a real state, and saying
		// so is more useful than omitting the section and leaving a reader to
		// assume validation passed.
		fmt.Fprintf(b, "**Held-out validation could not run**: %v\n\n", err)
		return
	}

	b.WriteString("### Held-out validation\n\n")
	b.WriteString("Each point excluded from the fit in turn, then predicted from the rest.\n")
	b.WriteString("The endpoints are the informative ones: they lie outside the remaining\n")
	b.WriteString("points' range, which is the situation every published projection is in.\n\n")
	b.WriteString("| Held out | Measured heap | Predicted heap | Error | Goroutine error | Outside the fit's range |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	var worst float64
	for _, v := range vs {
		worst = max(worst, v.HeapErrorFraction)
		fmt.Fprintf(b, "| %d | %s | %s | %.2f%% | %.2f%% | %s |\n",
			v.Workspaces, humanBytes(v.MeasuredHeapBytes), humanBytes(v.PredictedHeapBytes),
			v.HeapErrorFraction*100, v.GoroutineErrorFraction*100, yesNo(v.Extrapolated))
	}
	fmt.Fprintf(b, "\n**Worst heap prediction error: %.2f%%.**\n\n", worst*100)
}

func writeProjection(b *strings.Builder, m scaleharness.Model, fleets []int) {
	b.WriteString("### Projected sizing\n\n")
	b.WriteString("| Workspaces | Live heap | Stacks | Footprint (sizing figure) | Goroutines | Extrapolation factor |\n")
	b.WriteString("|---|---|---|---|---|---|\n")

	var basis string
	for _, n := range fleets {
		p, err := m.Predict(m.Regime.Shape, n)
		if err != nil {
			fmt.Fprintf(b, "| %d | — | — | — | — | declined: %v |\n", n, err)
			continue
		}
		basis = p.ResidentBasis
		factor := "measured range"
		if p.Extrapolated {
			factor = fmt.Sprintf("%.1f×", p.ExtrapolationFactor)
		}
		stacks := "—"
		if p.StackBytes > 0 {
			stacks = humanBytes(p.StackBytes)
		}
		fmt.Fprintf(b, "| %d | %s | %s | %s | %.0f | %s |\n",
			p.Workspaces, humanBytes(p.HeapBytes), stacks, humanBytes(p.ResidentBytes), p.Goroutines, factor)
	}

	if strings.Contains(basis, "measured") {
		fmt.Fprintf(b, "\nFootprint basis: %s. This is what the Go runtime obtained from the OS,\n"+
			"which over-estimates resident set size — the runtime returns pages lazily —\n"+
			"and is the right direction to err in when setting a limit.\n\n", basis)
		return
	}
	fmt.Fprintf(b, "\nFootprint basis: %s — `live × (1 + GOGC/100) + %s`. This run predates the\n"+
		"recording of `MemStats.Sys`, so goroutine stacks are covered by a flat\n"+
		"allowance rather than measured, and the figure understates a large fleet.\n\n",
		basis, humanBytes(float64(scaleharness.DefaultNonHeapBytes)))
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func parseInts(s string) ([]int, error) {
	var out []int
	for _, part := range strings.Split(s, ",") {
		n, err := strconv.Atoi(strings.TrimSpace(part))
		if err != nil {
			return nil, fmt.Errorf("parsing fleet sizes %q: %w", s, err)
		}
		out = append(out, n)
	}
	return out, nil
}

func humanBytes(b float64) string {
	const unit = 1024.0
	if b < unit {
		return fmt.Sprintf("%.0f B", b)
	}
	div, exp := unit, 0
	for n := b / unit; n >= unit && exp < 3; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.2f %ciB", b/div, "KMGT"[exp])
}
